{
  "schema_version": "1.4.0",
  "id": "GHSA-4cm9-63x5-55wm",
  "modified": "2024-03-21T03:34:05Z",
  "published": "2022-05-24T19:06:41Z",
  "aliases": [
    "CVE-2021-35958"
  ],
  "details": "** DISPUTED ** TensorFlow through 2.5.0 allows attackers to overwrite arbitrary files via a crafted archive when tf.keras.utils.get_file is used with extract=True. NOTE: the vendor's position is that tf.keras.utils.get_file is not intended for untrusted archives.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-35958"
    },
    {
      "type": "WEB",
      "url": "https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/blob/b8cad4c631096a34461ff8a07840d5f4d123ce32/tensorflow/python/keras/README.md"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/blob/b8cad4c631096a34461ff8a07840d5f4d123ce32/tensorflow/python/keras/utils/data_utils.py#L137"
    },
    {
      "type": "WEB",
      "url": "https://keras.io/api"
    },
    {
      "type": "WEB",
      "url": "https://vuln.ryotak.me/advisories/52"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-22",
      "CWE-668"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2021-06-30T01:15:00Z"
  }
}