{
  "schema_version": "1.4.0",
  "id": "GHSA-3hwm-p7rr-jj9v",
  "modified": "2025-01-18T00:30:48Z",
  "published": "2025-01-18T00:30:48Z",
  "aliases": [
    "CVE-2021-21158"
  ],
  "details": "Rejected reason: Further investigation determines issue is not within scope of this CNA",
  "severity": [],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-21158"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-01-17T23:15:12Z"
  }
}