{
  "schema_version": "1.4.0",
  "id": "GHSA-f2gq-74f6-v2f7",
  "modified": "2023-11-10T06:30:18Z",
  "published": "2023-11-10T06:30:18Z",
  "aliases": [
    "CVE-2023-45167"
  ],
  "details": "IBM AIX's 7.3 Python implementation could allow a non-privileged local user to exploit a vulnerability to cause a denial of service.  IBM X-Force ID:  267965.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45167"
    },
    {
      "type": "WEB",
      "url": "https://aix.software.ibm.com/aix/efixes/security/python_advisory6.asc"
    },
    {
      "type": "WEB",
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/267965"
    },
    {
      "type": "WEB",
      "url": "https://www.ibm.com/support/pages/node/7068084"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-20",
      "CWE-400"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-11-10T04:15:07Z"
  }
}