{
  "schema_version": "1.4.0",
  "id": "GHSA-qhmw-m62m-p9xh",
  "modified": "2022-05-13T01:19:56Z",
  "published": "2022-05-13T01:19:56Z",
  "aliases": [
    "CVE-2018-20718"
  ],
  "details": "In Pydio before 8.2.2, an attack is possible via PHP Object Injection because a user is allowed to use the $phpserial$a:0:{} syntax to store a preference. An attacker either needs a \"public link\" of a file, or access to any unprivileged user account for creation of such a link.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-20718"
    },
    {
      "type": "WEB",
      "url": "https://blog.ripstech.com/2018/pydio-unauthenticated-remote-code-execution"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-502"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2019-01-15T16:29:00Z"
  }
}