{
  "schema_version": "1.4.0",
  "id": "GHSA-v78v-g6p5-pp8w",
  "modified": "2024-01-18T03:30:24Z",
  "published": "2024-01-18T03:30:24Z",
  "aliases": [
    "CVE-2024-0654"
  ],
  "details": "A vulnerability, which was classified as problematic, was found in DeepFaceLab pretrained DF.wf.288res.384.92.72.22. Affected is an unknown function of the file mainscripts/Util.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. VDB-251382 is the identifier assigned to this vulnerability.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-0654"
    },
    {
      "type": "WEB",
      "url": "https://github.com/bayuncao/vul-cve-4"
    },
    {
      "type": "WEB",
      "url": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?ctiid.251382"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?id.251382"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-502"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-01-18T01:15:44Z"
  }
}