{
  "schema_version": "1.4.0",
  "id": "GHSA-76fj-hmj4-2w99",
  "modified": "2022-06-16T00:00:27Z",
  "published": "2022-06-09T00:00:18Z",
  "aliases": [
    "CVE-2022-30877"
  ],
  "details": "The keep for python, as distributed on PyPI, included a code-execution backdoor inserted by a third party. The current version, without this backdoor, is 1.2.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-30877"
    },
    {
      "type": "WEB",
      "url": "https://github.com/OrkoHunter/keep/issues/85"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/keep"
    },
    {
      "type": "WEB",
      "url": "http://pypi.doubanio.com/simple/request"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-94"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-06-08T18:15:00Z"
  }
}