{
  "schema_version": "1.4.0",
  "id": "GHSA-3frq-wgwx-p958",
  "modified": "2022-07-13T00:01:41Z",
  "published": "2022-05-24T19:16:10Z",
  "aliases": [
    "CVE-2021-41325"
  ],
  "details": "Broken access control for user creation in Pydio Cells 2.2.9 allows remote anonymous users to create standard users via the profile parameter. (In addition, such users can be granted several admin permissions via the Roles parameter.)",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41325"
    },
    {
      "type": "WEB",
      "url": "https://charonv.net/Pydio-Broken-Access-Control"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pydio/cells/releases/tag/v2.2.12"
    },
    {
      "type": "WEB",
      "url": "https://pydio.com/fr/community/releases/pydio-cells/pydio-cells-enterprise-2212"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-863"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2021-09-30T19:15:00Z"
  }
}